//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnAPIService_Client_Example.SnAPIService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NeighbourCountResult", Namespace="http://schemas.datacontract.org/2004/07/SnApiWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class NeighbourCountResult : SnAPIService_Client_Example.SnAPIService.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConceptFullySpecifiedNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ConceptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NeighbourCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PorCHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> RelTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelTypeFullySpecifiedNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConceptFullySpecifiedName {
            get {
                return this.ConceptFullySpecifiedNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConceptFullySpecifiedNameField, value) != true)) {
                    this.ConceptFullySpecifiedNameField = value;
                    this.RaisePropertyChanged("ConceptFullySpecifiedName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ConceptId {
            get {
                return this.ConceptIdField;
            }
            set {
                if ((this.ConceptIdField.Equals(value) != true)) {
                    this.ConceptIdField = value;
                    this.RaisePropertyChanged("ConceptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NeighbourCount {
            get {
                return this.NeighbourCountField;
            }
            set {
                if ((this.NeighbourCountField.Equals(value) != true)) {
                    this.NeighbourCountField = value;
                    this.RaisePropertyChanged("NeighbourCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PorCH {
            get {
                return this.PorCHField;
            }
            set {
                if ((object.ReferenceEquals(this.PorCHField, value) != true)) {
                    this.PorCHField = value;
                    this.RaisePropertyChanged("PorCH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> RelType {
            get {
                return this.RelTypeField;
            }
            set {
                if ((this.RelTypeField.Equals(value) != true)) {
                    this.RelTypeField = value;
                    this.RaisePropertyChanged("RelType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelTypeFullySpecifiedName {
            get {
                return this.RelTypeFullySpecifiedNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RelTypeFullySpecifiedNameField, value) != true)) {
                    this.RelTypeFullySpecifiedNameField = value;
                    this.RaisePropertyChanged("RelTypeFullySpecifiedName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.ComplexObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.RelType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.MapSet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.Status))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.Suffix))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.Favourite))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.SubSet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.Concept))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.ICD10Code))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.Description))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.ICD10Description))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.Neighbour))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.ICD10Children))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.NeighbourCountResult))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComplexObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.RelType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.MapSet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.Status))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.Suffix))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.Favourite))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.SubSet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.Concept))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.ICD10Code))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.Description))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.ICD10Description))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.Neighbour))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.ICD10Children))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SnAPIService_Client_Example.SnAPIService.NeighbourCountResult))]
    public partial class ComplexObject : SnAPIService_Client_Example.SnAPIService.StructuralObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelType", Namespace="http://schemas.datacontract.org/2004/07/SnApiWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class RelType : SnAPIService_Client_Example.SnAPIService.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> FrequencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullySpecifiedNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> RelationshipTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Frequency {
            get {
                return this.FrequencyField;
            }
            set {
                if ((this.FrequencyField.Equals(value) != true)) {
                    this.FrequencyField = value;
                    this.RaisePropertyChanged("Frequency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullySpecifiedName {
            get {
                return this.FullySpecifiedNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullySpecifiedNameField, value) != true)) {
                    this.FullySpecifiedNameField = value;
                    this.RaisePropertyChanged("FullySpecifiedName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> RelationshipType {
            get {
                return this.RelationshipTypeField;
            }
            set {
                if ((this.RelationshipTypeField.Equals(value) != true)) {
                    this.RelationshipTypeField = value;
                    this.RaisePropertyChanged("RelationshipType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MapSet", Namespace="http://schemas.datacontract.org/2004/07/SnApiWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class MapSet : SnAPIService_Client_Example.SnAPIService.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MapSetIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MapSetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MapSetRealmIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> MapSetRuleTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MapSetSchemeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MapSetSchemeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MapSetSchemeVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MapSetSeparatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> MapSetTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MapSetId {
            get {
                return this.MapSetIdField;
            }
            set {
                if ((this.MapSetIdField.Equals(value) != true)) {
                    this.MapSetIdField = value;
                    this.RaisePropertyChanged("MapSetId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MapSetName {
            get {
                return this.MapSetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MapSetNameField, value) != true)) {
                    this.MapSetNameField = value;
                    this.RaisePropertyChanged("MapSetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MapSetRealmId {
            get {
                return this.MapSetRealmIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MapSetRealmIdField, value) != true)) {
                    this.MapSetRealmIdField = value;
                    this.RaisePropertyChanged("MapSetRealmId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> MapSetRuleType {
            get {
                return this.MapSetRuleTypeField;
            }
            set {
                if ((this.MapSetRuleTypeField.Equals(value) != true)) {
                    this.MapSetRuleTypeField = value;
                    this.RaisePropertyChanged("MapSetRuleType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MapSetSchemeId {
            get {
                return this.MapSetSchemeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MapSetSchemeIdField, value) != true)) {
                    this.MapSetSchemeIdField = value;
                    this.RaisePropertyChanged("MapSetSchemeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MapSetSchemeName {
            get {
                return this.MapSetSchemeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MapSetSchemeNameField, value) != true)) {
                    this.MapSetSchemeNameField = value;
                    this.RaisePropertyChanged("MapSetSchemeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MapSetSchemeVersion {
            get {
                return this.MapSetSchemeVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.MapSetSchemeVersionField, value) != true)) {
                    this.MapSetSchemeVersionField = value;
                    this.RaisePropertyChanged("MapSetSchemeVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MapSetSeparator {
            get {
                return this.MapSetSeparatorField;
            }
            set {
                if ((object.ReferenceEquals(this.MapSetSeparatorField, value) != true)) {
                    this.MapSetSeparatorField = value;
                    this.RaisePropertyChanged("MapSetSeparator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> MapSetType {
            get {
                return this.MapSetTypeField;
            }
            set {
                if ((this.MapSetTypeField.Equals(value) != true)) {
                    this.MapSetTypeField = value;
                    this.RaisePropertyChanged("MapSetType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/SnApiWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Status : SnAPIService_Client_Example.SnAPIService.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte ConceptStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte ConceptStatus {
            get {
                return this.ConceptStatusField;
            }
            set {
                if ((this.ConceptStatusField.Equals(value) != true)) {
                    this.ConceptStatusField = value;
                    this.RaisePropertyChanged("ConceptStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusName {
            get {
                return this.StatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusNameField, value) != true)) {
                    this.StatusNameField = value;
                    this.RaisePropertyChanged("StatusName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Suffix", Namespace="http://schemas.datacontract.org/2004/07/SnApiWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Suffix : SnAPIService_Client_Example.SnAPIService.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FrequencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string suffixField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Frequency {
            get {
                return this.FrequencyField;
            }
            set {
                if ((this.FrequencyField.Equals(value) != true)) {
                    this.FrequencyField = value;
                    this.RaisePropertyChanged("Frequency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string suffix {
            get {
                return this.suffixField;
            }
            set {
                if ((object.ReferenceEquals(this.suffixField, value) != true)) {
                    this.suffixField = value;
                    this.RaisePropertyChanged("suffix");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Favourite", Namespace="http://schemas.datacontract.org/2004/07/SnApiWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Favourite : SnAPIService_Client_Example.SnAPIService.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> FavouriteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FavouriteNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MemberCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrivateSharedFlagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> FavouriteId {
            get {
                return this.FavouriteIdField;
            }
            set {
                if ((this.FavouriteIdField.Equals(value) != true)) {
                    this.FavouriteIdField = value;
                    this.RaisePropertyChanged("FavouriteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FavouriteName {
            get {
                return this.FavouriteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FavouriteNameField, value) != true)) {
                    this.FavouriteNameField = value;
                    this.RaisePropertyChanged("FavouriteName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MemberCount {
            get {
                return this.MemberCountField;
            }
            set {
                if ((this.MemberCountField.Equals(value) != true)) {
                    this.MemberCountField = value;
                    this.RaisePropertyChanged("MemberCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrivateSharedFlag {
            get {
                return this.PrivateSharedFlagField;
            }
            set {
                if ((object.ReferenceEquals(this.PrivateSharedFlagField, value) != true)) {
                    this.PrivateSharedFlagField = value;
                    this.RaisePropertyChanged("PrivateSharedFlag");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubSet", Namespace="http://schemas.datacontract.org/2004/07/SnApiWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SubSet : SnAPIService_Client_Example.SnAPIService.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MemberCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> SubSetIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SubSetTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubSetnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MemberCount {
            get {
                return this.MemberCountField;
            }
            set {
                if ((this.MemberCountField.Equals(value) != true)) {
                    this.MemberCountField = value;
                    this.RaisePropertyChanged("MemberCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> SubSetId {
            get {
                return this.SubSetIdField;
            }
            set {
                if ((this.SubSetIdField.Equals(value) != true)) {
                    this.SubSetIdField = value;
                    this.RaisePropertyChanged("SubSetId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SubSetType {
            get {
                return this.SubSetTypeField;
            }
            set {
                if ((this.SubSetTypeField.Equals(value) != true)) {
                    this.SubSetTypeField = value;
                    this.RaisePropertyChanged("SubSetType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubSetname {
            get {
                return this.SubSetnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubSetnameField, value) != true)) {
                    this.SubSetnameField = value;
                    this.RaisePropertyChanged("SubSetname");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Concept", Namespace="http://schemas.datacontract.org/2004/07/SnApiWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Concept : SnAPIService_Client_Example.SnAPIService.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CTV3IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ConceptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte ConceptStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullySpecifiedNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> IsPrimitiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LenStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> RootConceptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SNOMEDIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> weightField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTV3ID {
            get {
                return this.CTV3IDField;
            }
            set {
                if ((object.ReferenceEquals(this.CTV3IDField, value) != true)) {
                    this.CTV3IDField = value;
                    this.RaisePropertyChanged("CTV3ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ConceptId {
            get {
                return this.ConceptIdField;
            }
            set {
                if ((this.ConceptIdField.Equals(value) != true)) {
                    this.ConceptIdField = value;
                    this.RaisePropertyChanged("ConceptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte ConceptStatus {
            get {
                return this.ConceptStatusField;
            }
            set {
                if ((this.ConceptStatusField.Equals(value) != true)) {
                    this.ConceptStatusField = value;
                    this.RaisePropertyChanged("ConceptStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullySpecifiedName {
            get {
                return this.FullySpecifiedNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullySpecifiedNameField, value) != true)) {
                    this.FullySpecifiedNameField = value;
                    this.RaisePropertyChanged("FullySpecifiedName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> IsPrimitive {
            get {
                return this.IsPrimitiveField;
            }
            set {
                if ((this.IsPrimitiveField.Equals(value) != true)) {
                    this.IsPrimitiveField = value;
                    this.RaisePropertyChanged("IsPrimitive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LenStr {
            get {
                return this.LenStrField;
            }
            set {
                if ((this.LenStrField.Equals(value) != true)) {
                    this.LenStrField = value;
                    this.RaisePropertyChanged("LenStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> RootConceptId {
            get {
                return this.RootConceptIdField;
            }
            set {
                if ((this.RootConceptIdField.Equals(value) != true)) {
                    this.RootConceptIdField = value;
                    this.RaisePropertyChanged("RootConceptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SNOMEDID {
            get {
                return this.SNOMEDIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SNOMEDIDField, value) != true)) {
                    this.SNOMEDIDField = value;
                    this.RaisePropertyChanged("SNOMEDID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string r {
            get {
                return this.rField;
            }
            set {
                if ((object.ReferenceEquals(this.rField, value) != true)) {
                    this.rField = value;
                    this.RaisePropertyChanged("r");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> weight {
            get {
                return this.weightField;
            }
            set {
                if ((this.weightField.Equals(value) != true)) {
                    this.weightField = value;
                    this.RaisePropertyChanged("weight");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ICD10Code", Namespace="http://schemas.datacontract.org/2004/07/SnApiWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ICD10Code : SnAPIService_Client_Example.SnAPIService.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LenStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> weightField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODE {
            get {
                return this.CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.CODEField, value) != true)) {
                    this.CODEField = value;
                    this.RaisePropertyChanged("CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPTION {
            get {
                return this.DESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPTIONField, value) != true)) {
                    this.DESCRIPTIONField = value;
                    this.RaisePropertyChanged("DESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LenStr {
            get {
                return this.LenStrField;
            }
            set {
                if ((this.LenStrField.Equals(value) != true)) {
                    this.LenStrField = value;
                    this.RaisePropertyChanged("LenStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string r {
            get {
                return this.rField;
            }
            set {
                if ((object.ReferenceEquals(this.rField, value) != true)) {
                    this.rField = value;
                    this.RaisePropertyChanged("r");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> weight {
            get {
                return this.weightField;
            }
            set {
                if ((this.weightField.Equals(value) != true)) {
                    this.weightField = value;
                    this.RaisePropertyChanged("weight");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Description", Namespace="http://schemas.datacontract.org/2004/07/SnApiWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Description : SnAPIService_Client_Example.SnAPIService.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ConceptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DescriptionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte DescriptionStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte DescriptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> IbitialCapitalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TermField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ConceptId {
            get {
                return this.ConceptIdField;
            }
            set {
                if ((this.ConceptIdField.Equals(value) != true)) {
                    this.ConceptIdField = value;
                    this.RaisePropertyChanged("ConceptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DescriptionId {
            get {
                return this.DescriptionIdField;
            }
            set {
                if ((this.DescriptionIdField.Equals(value) != true)) {
                    this.DescriptionIdField = value;
                    this.RaisePropertyChanged("DescriptionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte DescriptionStatus {
            get {
                return this.DescriptionStatusField;
            }
            set {
                if ((this.DescriptionStatusField.Equals(value) != true)) {
                    this.DescriptionStatusField = value;
                    this.RaisePropertyChanged("DescriptionStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte DescriptionType {
            get {
                return this.DescriptionTypeField;
            }
            set {
                if ((this.DescriptionTypeField.Equals(value) != true)) {
                    this.DescriptionTypeField = value;
                    this.RaisePropertyChanged("DescriptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> IbitialCapitalStatus {
            get {
                return this.IbitialCapitalStatusField;
            }
            set {
                if ((this.IbitialCapitalStatusField.Equals(value) != true)) {
                    this.IbitialCapitalStatusField = value;
                    this.RaisePropertyChanged("IbitialCapitalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageCode {
            get {
                return this.LanguageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageCodeField, value) != true)) {
                    this.LanguageCodeField = value;
                    this.RaisePropertyChanged("LanguageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Term {
            get {
                return this.TermField;
            }
            set {
                if ((object.ReferenceEquals(this.TermField, value) != true)) {
                    this.TermField = value;
                    this.RaisePropertyChanged("Term");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ICD10Description", Namespace="http://schemas.datacontract.org/2004/07/SnApiWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ICD10Description : SnAPIService_Client_Example.SnAPIService.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALT_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TREE_DESCRIPTIONField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALT_CODE {
            get {
                return this.ALT_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ALT_CODEField, value) != true)) {
                    this.ALT_CODEField = value;
                    this.RaisePropertyChanged("ALT_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODE {
            get {
                return this.CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.CODEField, value) != true)) {
                    this.CODEField = value;
                    this.RaisePropertyChanged("CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPTION {
            get {
                return this.DESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPTIONField, value) != true)) {
                    this.DESCRIPTIONField = value;
                    this.RaisePropertyChanged("DESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TREE_DESCRIPTION {
            get {
                return this.TREE_DESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.TREE_DESCRIPTIONField, value) != true)) {
                    this.TREE_DESCRIPTIONField = value;
                    this.RaisePropertyChanged("TREE_DESCRIPTION");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Neighbour", Namespace="http://schemas.datacontract.org/2004/07/SnApiWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Neighbour : SnAPIService_Client_Example.SnAPIService.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> NameSpaceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NeighbourConceptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NeighbourFSNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PorCHorSField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> NameSpaceID {
            get {
                return this.NameSpaceIDField;
            }
            set {
                if ((this.NameSpaceIDField.Equals(value) != true)) {
                    this.NameSpaceIDField = value;
                    this.RaisePropertyChanged("NameSpaceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NeighbourConceptId {
            get {
                return this.NeighbourConceptIdField;
            }
            set {
                if ((this.NeighbourConceptIdField.Equals(value) != true)) {
                    this.NeighbourConceptIdField = value;
                    this.RaisePropertyChanged("NeighbourConceptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NeighbourFSN {
            get {
                return this.NeighbourFSNField;
            }
            set {
                if ((object.ReferenceEquals(this.NeighbourFSNField, value) != true)) {
                    this.NeighbourFSNField = value;
                    this.RaisePropertyChanged("NeighbourFSN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PorCHorS {
            get {
                return this.PorCHorSField;
            }
            set {
                if ((object.ReferenceEquals(this.PorCHorSField, value) != true)) {
                    this.PorCHorSField = value;
                    this.RaisePropertyChanged("PorCHorS");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ICD10Children", Namespace="http://schemas.datacontract.org/2004/07/SnApiWcfService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ICD10Children : SnAPIService_Client_Example.SnAPIService.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALT_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RELATIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TREE_DESCRIPTIONField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALT_CODE {
            get {
                return this.ALT_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ALT_CODEField, value) != true)) {
                    this.ALT_CODEField = value;
                    this.RaisePropertyChanged("ALT_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODE {
            get {
                return this.CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.CODEField, value) != true)) {
                    this.CODEField = value;
                    this.RaisePropertyChanged("CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPTION {
            get {
                return this.DESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPTIONField, value) != true)) {
                    this.DESCRIPTIONField = value;
                    this.RaisePropertyChanged("DESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RELATION {
            get {
                return this.RELATIONField;
            }
            set {
                if ((object.ReferenceEquals(this.RELATIONField, value) != true)) {
                    this.RELATIONField = value;
                    this.RaisePropertyChanged("RELATION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TREE_DESCRIPTION {
            get {
                return this.TREE_DESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.TREE_DESCRIPTIONField, value) != true)) {
                    this.TREE_DESCRIPTIONField = value;
                    this.RaisePropertyChanged("TREE_DESCRIPTION");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SnAPIService.ISnApiService")]
    public interface ISnApiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/CreateFavourite", ReplyAction="http://tempuri.org/ISnApiService/CreateFavouriteResponse")]
        int CreateFavourite(string name, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/SetFavouritePrivateSharedFlag", ReplyAction="http://tempuri.org/ISnApiService/SetFavouritePrivateSharedFlagResponse")]
        void SetFavouritePrivateSharedFlag(int id, char flag, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/DeleteFavourite", ReplyAction="http://tempuri.org/ISnApiService/DeleteFavouriteResponse")]
        void DeleteFavourite(int id, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/RenameFavourite", ReplyAction="http://tempuri.org/ISnApiService/RenameFavouriteResponse")]
        void RenameFavourite(int id, string name, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/RegisterUser", ReplyAction="http://tempuri.org/ISnApiService/RegisterUserResponse")]
        string RegisterUser(string orgGuid, string userGuid, string name, string fullName, string email, string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/UnregisterUser", ReplyAction="http://tempuri.org/ISnApiService/UnregisterUserResponse")]
        void UnregisterUser(string orgGuid, string userGuid, string unregisterUserGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/GetNeighbourCount", ReplyAction="http://tempuri.org/ISnApiService/GetNeighbourCountResponse")]
        SnAPIService_Client_Example.SnAPIService.NeighbourCountResult[] GetNeighbourCount(long conceptId, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/GetRelTypes", ReplyAction="http://tempuri.org/ISnApiService/GetRelTypesResponse")]
        SnAPIService_Client_Example.SnAPIService.RelType[] GetRelTypes(string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/GetCrossMapSet", ReplyAction="http://tempuri.org/ISnApiService/GetCrossMapSetResponse")]
        SnAPIService_Client_Example.SnAPIService.MapSet[] GetCrossMapSet(string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/GetStatus", ReplyAction="http://tempuri.org/ISnApiService/GetStatusResponse")]
        SnAPIService_Client_Example.SnAPIService.Status[] GetStatus(string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/GetSuffixes", ReplyAction="http://tempuri.org/ISnApiService/GetSuffixesResponse")]
        SnAPIService_Client_Example.SnAPIService.Suffix[] GetSuffixes(string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/GetFavourites", ReplyAction="http://tempuri.org/ISnApiService/GetFavouritesResponse")]
        SnAPIService_Client_Example.SnAPIService.Favourite[] GetFavourites(string showEmpty, string includeShared, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/GetSubSets", ReplyAction="http://tempuri.org/ISnApiService/GetSubSetsResponse")]
        SnAPIService_Client_Example.SnAPIService.SubSet[] GetSubSets(string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/SearchConcepts", ReplyAction="http://tempuri.org/ISnApiService/SearchConceptsResponse")]
        SnAPIService_Client_Example.SnAPIService.Concept[] SearchConcepts(string text, string descendentId, string status, string ancestorId, string saveToFavouriteId, string targetCodes, string mapSetId, string subsets, string favorites, string suffix, string namespaces, int maxResults, int matchType, string searchMode, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/SearchICD10Codes", ReplyAction="http://tempuri.org/ISnApiService/SearchICD10CodesResponse")]
        SnAPIService_Client_Example.SnAPIService.ICD10Code[] SearchICD10Codes(string text, int maxResults, int matchType, string SearchMode, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/SearchConceptsCount", ReplyAction="http://tempuri.org/ISnApiService/SearchConceptsCountResponse")]
        int SearchConceptsCount(string text, string descendentId, string status, string ancestorId, string targetCodes, string mapSetId, string subsets, string favorites, string suffix, string namespaces, int matchType, string searchType, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/GetConcept", ReplyAction="http://tempuri.org/ISnApiService/GetConceptResponse")]
        SnAPIService_Client_Example.SnAPIService.Concept[] GetConcept(string conceptId, string nameSpace, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/GetDescription", ReplyAction="http://tempuri.org/ISnApiService/GetDescriptionResponse")]
        SnAPIService_Client_Example.SnAPIService.Description[] GetDescription(long conceptId, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/GetICD10Description", ReplyAction="http://tempuri.org/ISnApiService/GetICD10DescriptionResponse")]
        SnAPIService_Client_Example.SnAPIService.ICD10Description[] GetICD10Description(string conceptId, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/GetNeighbours", ReplyAction="http://tempuri.org/ISnApiService/GetNeighboursResponse")]
        SnAPIService_Client_Example.SnAPIService.Neighbour[] GetNeighbours(long conceptId, string nameSpace, int relType, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/GetICD10Children", ReplyAction="http://tempuri.org/ISnApiService/GetICD10ChildrenResponse")]
        SnAPIService_Client_Example.SnAPIService.ICD10Children[] GetICD10Children(string conceptId, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/ManageFavourites", ReplyAction="http://tempuri.org/ISnApiService/ManageFavouritesResponse")]
        void ManageFavourites(string action, int favouriteId, string keyList, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/SetConfigValue", ReplyAction="http://tempuri.org/ISnApiService/SetConfigValueResponse")]
        void SetConfigValue(string key, string value, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnApiService/GetSnoflakeURL", ReplyAction="http://tempuri.org/ISnApiService/GetSnoflakeURLResponse")]
        string GetSnoflakeURL(string guid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISnApiServiceChannel : SnAPIService_Client_Example.SnAPIService.ISnApiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SnApiServiceClient : System.ServiceModel.ClientBase<SnAPIService_Client_Example.SnAPIService.ISnApiService>, SnAPIService_Client_Example.SnAPIService.ISnApiService {
        
        public SnApiServiceClient() {
        }
        
        public SnApiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SnApiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SnApiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SnApiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CreateFavourite(string name, string guid) {
            return base.Channel.CreateFavourite(name, guid);
        }
        
        public void SetFavouritePrivateSharedFlag(int id, char flag, string guid) {
            base.Channel.SetFavouritePrivateSharedFlag(id, flag, guid);
        }
        
        public void DeleteFavourite(int id, string guid) {
            base.Channel.DeleteFavourite(id, guid);
        }
        
        public void RenameFavourite(int id, string name, string guid) {
            base.Channel.RenameFavourite(id, name, guid);
        }
        
        public string RegisterUser(string orgGuid, string userGuid, string name, string fullName, string email, string country) {
            return base.Channel.RegisterUser(orgGuid, userGuid, name, fullName, email, country);
        }
        
        public void UnregisterUser(string orgGuid, string userGuid, string unregisterUserGuid) {
            base.Channel.UnregisterUser(orgGuid, userGuid, unregisterUserGuid);
        }
        
        public SnAPIService_Client_Example.SnAPIService.NeighbourCountResult[] GetNeighbourCount(long conceptId, string guid) {
            return base.Channel.GetNeighbourCount(conceptId, guid);
        }
        
        public SnAPIService_Client_Example.SnAPIService.RelType[] GetRelTypes(string guid) {
            return base.Channel.GetRelTypes(guid);
        }
        
        public SnAPIService_Client_Example.SnAPIService.MapSet[] GetCrossMapSet(string guid) {
            return base.Channel.GetCrossMapSet(guid);
        }
        
        public SnAPIService_Client_Example.SnAPIService.Status[] GetStatus(string guid) {
            return base.Channel.GetStatus(guid);
        }
        
        public SnAPIService_Client_Example.SnAPIService.Suffix[] GetSuffixes(string guid) {
            return base.Channel.GetSuffixes(guid);
        }
        
        public SnAPIService_Client_Example.SnAPIService.Favourite[] GetFavourites(string showEmpty, string includeShared, string guid) {
            return base.Channel.GetFavourites(showEmpty, includeShared, guid);
        }
        
        public SnAPIService_Client_Example.SnAPIService.SubSet[] GetSubSets(string guid) {
            return base.Channel.GetSubSets(guid);
        }
        
        public SnAPIService_Client_Example.SnAPIService.Concept[] SearchConcepts(string text, string descendentId, string status, string ancestorId, string saveToFavouriteId, string targetCodes, string mapSetId, string subsets, string favorites, string suffix, string namespaces, int maxResults, int matchType, string searchMode, string guid) {
            return base.Channel.SearchConcepts(text, descendentId, status, ancestorId, saveToFavouriteId, targetCodes, mapSetId, subsets, favorites, suffix, namespaces, maxResults, matchType, searchMode, guid);
        }
        
        public SnAPIService_Client_Example.SnAPIService.ICD10Code[] SearchICD10Codes(string text, int maxResults, int matchType, string SearchMode, string guid) {
            return base.Channel.SearchICD10Codes(text, maxResults, matchType, SearchMode, guid);
        }
        
        public int SearchConceptsCount(string text, string descendentId, string status, string ancestorId, string targetCodes, string mapSetId, string subsets, string favorites, string suffix, string namespaces, int matchType, string searchType, string guid) {
            return base.Channel.SearchConceptsCount(text, descendentId, status, ancestorId, targetCodes, mapSetId, subsets, favorites, suffix, namespaces, matchType, searchType, guid);
        }
        
        public SnAPIService_Client_Example.SnAPIService.Concept[] GetConcept(string conceptId, string nameSpace, string guid) {
            return base.Channel.GetConcept(conceptId, nameSpace, guid);
        }
        
        public SnAPIService_Client_Example.SnAPIService.Description[] GetDescription(long conceptId, string guid) {
            return base.Channel.GetDescription(conceptId, guid);
        }
        
        public SnAPIService_Client_Example.SnAPIService.ICD10Description[] GetICD10Description(string conceptId, string guid) {
            return base.Channel.GetICD10Description(conceptId, guid);
        }
        
        public SnAPIService_Client_Example.SnAPIService.Neighbour[] GetNeighbours(long conceptId, string nameSpace, int relType, string guid) {
            return base.Channel.GetNeighbours(conceptId, nameSpace, relType, guid);
        }
        
        public SnAPIService_Client_Example.SnAPIService.ICD10Children[] GetICD10Children(string conceptId, string guid) {
            return base.Channel.GetICD10Children(conceptId, guid);
        }
        
        public void ManageFavourites(string action, int favouriteId, string keyList, string guid) {
            base.Channel.ManageFavourites(action, favouriteId, keyList, guid);
        }
        
        public void SetConfigValue(string key, string value, string guid) {
            base.Channel.SetConfigValue(key, value, guid);
        }
        
        public string GetSnoflakeURL(string guid) {
            return base.Channel.GetSnoflakeURL(guid);
        }
    }
}
